language: ruby
dist: trusty
sudo: required

env:
  - TRAVIS_NODE_VERSION="6.9.4"

before_install:
  - nvm install $TRAVIS_NODE_VERSION

install:
  - npm install
  - bundle install

script:
  - npm run test
